# Determines if iCloud Drive is symlinked to ~/iCloud
icloud_enabled: false

# macOS-only utilities that don't get installed by a role
mac_homebrew_packages:
  # User-contributed docs for Unix commands
  # NOTE: no arm64 linux builds are available, so only install this on macOS
  - tlrc
  # for generating QR codes
  - qrtool

# Mac Apps to be installed with homebrew-cask
mac_cask_packages:
  # Password manager
  - 1password
  # Editor
  - visual-studio-code
  # Browsers
  - firefox
  # Maintained caffeinate wrapper
  - keepingyouawake
  # Utilities
  - bettertouchtool
  - appcleaner
  # VMs+Docker
  - orbstack
  # Media/Music
  - iina
  # Notetaking
  # - obsidian
  # Database client
  # - tableplus
  # Screen captures and recording
  - cleanshot
  # VPN
  # - tailscale-app
  # Color picker
  - pika
  # Malware scanner
  # - knockknock
  # Firewall
  # - lulu

# Mac-App-Store-only apps to be installed with mas
# Use App IDs found with `mas search <name>`
mac_mas_packages:
  # NOTE: the IDs can be found with `mas search <app name>`
  - { "id": 361304891, "name": "Numbers" }
