# Determines if iCloud Drive is symlinked to ~/iCloud
icloud_enabled: false

# macOS-only utilities that don't get installed by a role
mac_homebrew_packages: []

# Mac Apps to be installed with homebrew-cask
mac_cask_packages:
  # More resource-efficient Docker
  - orbstack
  # VPN
  - tailscale-app
  # Malware scanner
  - knockknock
