---
- name: Install rustup
  community.general.homebrew:
    name: rustup
    state: present

- name: Install stable Rust toolchain
  ansible.builtin.command: rustup-init -y
  args:
    creates: "{{ dotfiles_user_home }}/.cargo/bin/rustc"
  environment:
    RUSTUP_HOME: "{{ dotfiles_user_home }}/.rustup"
    CARGO_HOME: "{{ dotfiles_user_home }}/.cargo"
