alias py="python"
alias py3="python3"
alias ipy="ipython"
alias ipynb="ipython notebook"
alias jpnb="jupyter notebook"
alias pyserv2="python2 -m SimpleHTTPServer"
alias pyserv="python3 -m http.server"
alias pt="py.test"
alias nt="nosetests"
alias mn="python manage.py"
alias pipgrep="pip freeze | grep -i "
alias getpip="wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py && rm get-pip.py"

alias mkenv="pew new --python=python3 -i ipython -i jupyter "
alias mkenv2="pew new --python=python2 -i ipython -i jupyter "
alias wo="pew workon"
alias de="source deactivate"
