alias py="python"
alias ipy="ipython"
alias ipynb="ipython notebook"
alias jpnb="jupyter notebook"
alias pyserv="python3 -m http.server"
alias pt="pytest"
alias arg="all-repos-grep"
alias arf="all-repos-find-files"
alias ars="all-repos-sed"
alias pipgrep="pip freeze | grep -i "

alias pywhich="pyenv which"
