# NOTE: Each role is tagged so that we can select individual roles to run with ansible-playbook --tags

- name: Common provisioning
  hosts: all
  gather_facts: false
  roles:
    - { role: git, tags: ["git"] }
    - { role: package_manager, tags: ["package_manager"] }
    - { role: zsh, tags: ["zsh"] }
    - { role: python, tags: ["python"] }
    - { role: mise, tags: ["mise"] }
    - { role: rust, tags: ["rust"] }
    - { role: vim, tags: ["vim"] }
    - { role: eza, tags: ["eza"] }
    - { role: gsed, tags: ["gsed"] }
    - { role: bat, tags: ["bat"] }
    - { role: lctl, tags: ["lctl"] }
    - { role: macos, tags: ["macos"] }

- name: Local-only provisioning
  hosts: local
  roles:
    - { role: kubernetes, tags: ["kubernetes"] }
    - { role: jrnl, tags: ["jrnl"] }
    - { role: k9s, tags: ["k9s"] }

- name: Remote-only provisioning
  hosts: remote
  gather_facts: false
  pre_tasks:
    - name: Clone dotfiles repository
      ansible.builtin.git:
        repo: https://github.com/sloria/dotfiles.git
        dest: "{{ dotfiles_user_home }}/dotfiles"
        clone: yes
      when: inventory_hostname != 'localhost'
  roles:
    - { role: adguard, tags: ["adguard"] }
    - { role: ollama, tags: ["ollama"] }
