# NOTE: Each role is tagged so that we can select individual roles to run with ansible-playbook --tags

- name: OrbStack VM hardening
  hosts: orb
  become: true
  gather_facts: false
  roles:
    - { role: orb_lockdown, tags: ["orb_lockdown"] }

- name: Common provisioning
  hosts: all
  gather_facts: true
  roles:
    - { role: git, tags: ["git"] }
    - { role: gh, tags: ["gh"] }
    - { role: package_manager, tags: ["package_manager"] }
    - { role: zsh, tags: ["zsh"] }
    - { role: python, tags: ["python"] }
    - { role: mise, tags: ["mise"] }
    - { role: rust, tags: ["rust"] }
    - { role: neovim, tags: ["neovim"] }
    - { role: eza, tags: ["eza"] }
    - { role: bat, tags: ["bat"] }

- name: macOS provisioning # noqa: name[casing]
  hosts: mac
  roles:
    - { role: macos, tags: ["macos"] }
    - { role: lctl, tags: ["lctl"] }

- name: Local-only provisioning
  hosts: local
  roles:
    - { role: kubernetes, tags: ["kubernetes"] }
    - { role: jrnl, tags: ["jrnl"] }
    - { role: k9s, tags: ["k9s"] }
    - { role: ghostty, tags: ["ghostty"] }
