
- name: Collecting Facts
  hosts: remote
  gather_facts: yes

- name: Set up remote dev environments (clone)
  hosts: remote
  tasks:
    # The dotfiles must be cloned to the remote location so that all *.zsh files
    # and symlinks are present
    - name: Clone dotfiles repo
      git:
        repo: https://github.com/sloria/dotfiles.git
        dest: "{{dotfiles_user_home}}/dotfiles"

- name: Set up remote development environments (roles)
  hosts: remote
  # No prezto
  vars:
    zsh_prezto: no
  roles:
    - git
    - zsh
    - vim
    - tmux
