model_list:
  - model_name: Claude 3.7 Sonnet
    litellm_params:
      model: claude-3-7-sonnet-latest
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: GPT-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: GPT-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: o1-preview
    litellm_params:
      model: o1-preview
      api_key: os.environ/OPENAI_API_KEY

# https://docs.litellm.ai/docs/proxy/prod
general_settings:
  proxy_batch_write_at: 60 # Batch write spend updates every 60s
  database_connection_pool_limit: 10 # limit the number of database connections to = MAX Number of DB Connections/Number of instances of litellm proxy (Around 10-20 is good number)

litellm_settings:
  request_timeout: 600
  set_verbose: false
  json_logs: true
