---
- name: Make sure zsh is installed
  community.general.homebrew:
    name: zsh
    state: present

# Configuration
- name: Check if zshrc already exists
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  ansible.builtin.command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{ dotfiles_user_home }}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Import prezto tasks
  ansible.builtin.import_tasks: prezto.yml
  when: zsh_prezto

- name: Copy minimal zshrc
  ansible.builtin.copy:
    src: zshrc_minimal
    dest: "{{ dotfiles_user_home }}/.zshrc"
    mode: "0644"
  when: not zsh_prezto
