---
- name: Install zsh (macOS)
  community.general.homebrew:
    name: zsh
    state: present
  when: ansible_facts["system"] == "Darwin"

- name: Install zsh (Linux)
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true
  when: ansible_facts["os_family"] == "Debian"

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ dotfiles_user_home | basename }}"
    shell: /bin/zsh
  become: true
  when: ansible_facts["os_family"] == "Debian"

# Configuration
- name: Back up zshrc if it exists
  ansible.builtin.copy:
    src: "{{ dotfiles_user_home }}/.zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc.bak"
    remote_src: true
    force: false
    mode: "0644"
  failed_when: false
  changed_when: false

- name: Import prezto tasks
  ansible.builtin.import_tasks: prezto.yaml
  when: zsh_prezto

- name: Copy minimal zshrc
  ansible.builtin.copy:
    src: zshrc_minimal
    dest: "{{ dotfiles_user_home }}/.zshrc"
    mode: "0644"
  when: not zsh_prezto
