- name: Install mise with homebrew
  homebrew: name=mise state=present

- name: Create mise config directory
  ansible.builtin.file:
    path: "{{ '~/.config/mise' | expanduser }}"
    state: directory
    mode: '0755'

- name: Copy mise config file
  ansible.builtin.copy:
    src: "config.toml"
    dest: "{{ '~/.config/mise/config.toml' | expanduser }}"
