---
- name: Install git (macOS)
  community.general.homebrew:
    name: git
    state: present
  when: ansible_facts["system"] == "Darwin"

- name: Install git (Linux)
  ansible.builtin.apt:
    name: git
    state: present
  become: true
  when: ansible_facts["os_family"] == "Debian"

- name: Link global gitignore file
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: true

- name: Link gitattributes file
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/git/files/gitattributes_global.link"
    dest: "{{ dotfiles_user_home }}/.gitattributes_global"
    state: link
    force: true

- name: Back up gitconfig
  ansible.builtin.copy:
    src: "{{ dotfiles_user_home }}/.gitconfig"
    dest: "{{ dotfiles_user_home }}/.gitconfig.bak"
    remote_src: true
    force: false
    mode: "0644"
  failed_when: false
  changed_when: false

- name: Make sure gitconfig is up to date
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig"
    mode: "0644"

- name: Create gitconfig for alt account
  ansible.builtin.template:
    src: "gitconfig-alt.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig-alt"
    mode: "0644"
  when: git_alt_name is defined
