---
- name: Install git (macOS)
  community.general.homebrew:
    name: git
    state: present
  when: ansible_facts["system"] == "Darwin"

- name: Install git (Linux)
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_facts["os_family"] == "Debian"

- name: Link global gitignore file
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: true

- name: Link gitattributes file
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/git/files/gitattributes_global.link"
    dest: "{{ dotfiles_user_home }}/.gitattributes_global"
    state: link
    force: true

- name: Check if gitconfig exists
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  ansible.builtin.command: mv {{ dotfiles_user_home }}/.gitconfig {{ dotfiles_user_home }}/.gitconfig.bak
  args:
    creates: "{{ dotfiles_user_home }}/.gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Make sure gitconfig is up to date
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig"
    mode: "0644"

- name: Create gitconfig for alt account
  ansible.builtin.template:
    src: "gitconfig-alt.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig-alt"
    mode: "0644"
  when: git_alt_name is defined
