- name: Install neovim (macOS)
  ansible.builtin.package:
    name: neovim
    state: present
  when: ansible_facts["system"] == "Darwin"

- name: Add neovim PPA signing key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9DBB0BE9366964F134855E2255F96FCF8231B6DD
    dest: /etc/apt/keyrings/neovim-ppa.asc
    mode: "0644"

  when: ansible_facts["os_family"] == "Debian"

- name: Add neovim PPA
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/neovim-ppa.sources
    mode: "0644"
    content: |
      Types: deb
      URIs: https://ppa.launchpadcontent.net/neovim-ppa/unstable/ubuntu
      Suites: {{ ansible_facts["distribution_release"] }}
      Components: main
      Signed-By: /etc/apt/keyrings/neovim-ppa.asc
  when: ansible_facts["os_family"] == "Debian"

- name: Install neovim and build dependencies (Linux)
  ansible.builtin.apt:
    name:
      - neovim
      - build-essential # nvim-treesitter
      - npm # JS LSPs
      - python3-pip # Python LSPs
      - python3-venv # Python LSPs
      - unzip # binary LSPs
    state: present
    update_cache: true
  when: ansible_facts["os_family"] == "Debian"

- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.config"
    state: directory
    mode: "0755"

- name: Check if nvim config exists
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.config/nvim"
  register: nvim_stat
  failed_when: false

- name: Backup existing nvim config
  ansible.builtin.command: mv ~/.config/nvim ~/.config/nvim.bak
  changed_when: true
  when: nvim_stat.stat.exists and not nvim_stat.stat.islnk

- name: Symlink nvim config
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/neovim/files"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    state: link
