- name: Install neovim (macOS)
  ansible.builtin.package:
    name: neovim
    state: present
  when: ansible_facts["system"] == "Darwin"

- name: Install neovim AppImage (Linux)
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-{{ "arm64" if ansible_facts["architecture"] == "aarch64" else "x86_64" }}.appimage
    dest: /usr/local/bin/nvim
    mode: "0755"
  become: true
  when: ansible_facts["os_family"] == "Debian"

- name: Install neovim dependencies (Linux)
  ansible.builtin.apt:
    name:
      - build-essential # nvim-treesitter
      - fuse # AppImage support
      - npm # JS LSPs
      - python3-pip # Python LSPs
      - python3-venv # Python LSPs
      - unzip # binary LSPs
    state: present
    update_cache: true
  become: true
  when: ansible_facts["os_family"] == "Debian"

- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.config"
    state: directory
    mode: "0755"

- name: Check if nvim config exists
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.config/nvim"
  register: nvim_stat
  failed_when: false

- name: Backup existing nvim config
  ansible.builtin.command: mv ~/.config/nvim ~/.config/nvim.bak
  changed_when: true
  when: nvim_stat.stat.exists and not nvim_stat.stat.islnk

- name: Symlink nvim config
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/neovim/files"
    dest: "{{ dotfiles_user_home }}/.config/nvim"
    state: link
